<?php 
/**
 * ZF2 Buch Kapitel 13
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 13.1 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 13.1</h1>
<h3>Einsatz von <code>Zend\Session\Container</code></h3>
<pre>
&lt;?php
use Zend\Debug\Debug;
use Zend\Math\Rand;
use Zend\Session\Container;

$counter = new Container('counter');
$counter->number = $counter->number + 1;

$pizzaList = array('Pizza Salami', 'Pizza Mais', 'Pizza Melone');
$randomPizza = $pizzaList[array_rand($pizzaList)];
$randomCount = Rand::getInteger(1, 3);

$basket = new Container('basket');
if (!$basket->offsetExists('order')) {
    $basketData = array('rows' => array(), 'sum' => 0);
} else {
    $basketData = $basket->offsetGet('order');
}
$basketData['rows'][] = $randomCount . 'x ' . $randomPizza;
$basketData['sum' ]   = $basketData['sum'] + $randomCount;
$basket->offsetSet('order', $basketData);

Debug::dump($counter->number, '&lt;h5&gt;Zähler&lt;/h5&gt;');
Debug::dump($basket->order, '&lt;h5&gt;Warenkorb&lt;/h5&gt;');
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Debug\Debug;
use Zend\Math\Rand;
use Zend\Session\Container;

$counter = new Container('counter');
$counter->number = $counter->number + 1;

$pizzaList = array('Pizza Salami', 'Pizza Mais', 'Pizza Melone');
$randomPizza = $pizzaList[array_rand($pizzaList)];
$randomCount = Rand::getInteger(1, 3);

$basket = new Container('basket');
if (!$basket->offsetExists('order')) {
    $basketData = array('rows' => array(), 'sum' => 0);
} else {
    $basketData = $basket->offsetGet('order');
}
$basketData['rows'][] = $randomCount . 'x ' . $randomPizza;
$basketData['sum' ]   = $basketData['sum'] + $randomCount;
$basket->offsetSet('order', $basketData);

Debug::dump($counter->number, '<h5>Zähler</h5>');
Debug::dump($basket->order, '<h5>Warenkorb</h5>');
?>
</div>
</div>
