<?php 
/**
 * ZF2 Buch Kapitel 13
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 13.3 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 13.3</h1>
<h3>Session <code>SaveHandler</code> für <code>DbTableGateway</code> ändern</h3>
<pre>
&lt;?php
use Zend\Db\Adapter\Adapter;
use Zend\Db\TableGateway\TableGateway;
use Zend\Debug\Debug;
use Zend\Session\SessionManager;
use Zend\Session\SaveHandler\DbTableGateway;
use Zend\Session\SaveHandler\DbTableGatewayOptions;

$db = new Adapter(array(
    'driver'   => 'Pdo_Sqlite',
    'database' => LUIGI_ROOT . '/data/db/session.sqlite3.db',
));

$tableGateway   = new TableGateway('sessions', $db);
$options        = new DbTableGatewayOptions();
$saveHandler    = new DbTableGateway($tableGateway, $options);
$sessionManager = new SessionManager();
$sessionManager->setSaveHandler($saveHandler);
$sessionManager->start();
$sessionManager->writeClose();

$rows = $tableGateway->select();

foreach ($rows as $row) {
    Debug::dump($row->getArrayCopy());
}
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Db\Adapter\Adapter;
use Zend\Db\TableGateway\TableGateway;
use Zend\Debug\Debug;
use Zend\Session\SessionManager;
use Zend\Session\SaveHandler\DbTableGateway;
use Zend\Session\SaveHandler\DbTableGatewayOptions;

$db = new Adapter(array(
    'driver'   => 'Pdo_Sqlite',
    'database' => LUIGI_ROOT . '/data/db/session.sqlite3.db',
));

$tableGateway   = new TableGateway('sessions', $db);
$options        = new DbTableGatewayOptions();
$saveHandler    = new DbTableGateway($tableGateway, $options);
$sessionManager = new SessionManager();
$sessionManager->setSaveHandler($saveHandler);
$sessionManager->start();
$sessionManager->writeClose();

$rows = $tableGateway->select();

foreach ($rows as $row) {
    Debug::dump($row->getArrayCopy());
}
?>
</div>
</div>
