<?php 
/**
 * ZF2 Buch Kapitel 13
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 13.9 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 13.9</h1>
<h3>Passwortdatei <code>basic.pw</code> für Basic HTTP Authentication</h3>
<pre>
luigi:Luigis Pizza-Service:luigi
francesca:Luigis Pizza-Service:francesca
alessandro:Luigis Pizza-Service:alessandro
valentina:Luigis Pizza-Service:valentina
</pre>
</div>
</div>
