<?php 
/**
 * ZF2 Buch Kapitel 13
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 13.13 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 13.13</h1>
<h3>SQL-Dump für Datenbanktabelle <code>users</code> für SQLite3</h3>
<pre>
DROP TABLE users;
CREATE TABLE users (
    id integer primary key, 
    name varchar(32), 
    pass varchar(32)
);
INSERT INTO "users" 
     VALUES (1,'luigi','e9da82f4c252e7f1745ae88f2624fc07');
</pre>
</div>
</div>
