<?php 
/**
 * ZF2 Buch Kapitel 13
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 13.2 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 13.2</h1>
<h3>SQL-Dump für Datenbanktabelle <code>sessions</code> für SQLite3</h3>
<pre>
DROP TABLE sessions;
CREATE TABLE sessions (
    id varchar(32) primary key, 
    name varchar(32), 
    data text, 
    modified integer, 
    lifetime integer
);
</pre>
</div>
</div>
