<?php 
/**
 * ZF2 Buch Kapitel 13
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 13.12 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 13.12</h1>
<h3>Digest HTTP Authentication mit <code>Http</code> Adapter</h3>
<pre>
&lt;?php
use Zend\Authentication\Adapter\Http;
use Zend\Authentication\Adapter\Http\FileResolver;

$sm = $this->getHelperPluginManager()->getServiceLocator();

$response = $sm->get('response');
$request  = $sm->get('request');

$adapter = new Http(array(
    'accept_schemes' => 'digest',
    'realm'          => 'Luigis Pizza-Service',
    'digest_domains' => '/listing/listing1312',
    'nonce_timeout'  => 3600,
));

$digestResolver = new FileResolver();
$digestResolver->setFile(LUIGI_ROOT . '/data/auth/digest.pw');

$adapter->setDigestResolver($digestResolver);
$adapter->setRequest($request);
$adapter->setResponse($response);

$result = $adapter->authenticate();

if (!$result->isValid()) {
    echo 'Du kommst hier nicht rein!';
} else {
    $identity = $result->getIdentity();
    echo 'Herzlich Willkommen ' . $identity['username'] . '!';
}
</pre>
<h3>Ausgabe</h3>
<div class="well">
<?php 
use Zend\Authentication\Adapter\Http;
use Zend\Authentication\Adapter\Http\FileResolver;

$sm = $this->getHelperPluginManager()->getServiceLocator();

$response = $sm->get('response');
$request  = $sm->get('request');

$adapter = new Http(array(
    'accept_schemes' => 'digest',
    'realm'          => 'Luigis Pizza-Service',
    'digest_domains' => '/listing/listing1312',
    'nonce_timeout'  => 3600,
));

$digestResolver = new FileResolver();
$digestResolver->setFile(LUIGI_ROOT . '/data/auth/digest.pw');

$adapter->setDigestResolver($digestResolver);
$adapter->setRequest($request);
$adapter->setResponse($response);

$result = $adapter->authenticate();

if (!$result->isValid()) {
    echo 'Du kommst hier nicht rein!';
} else {
    $identity = $result->getIdentity();
    echo 'Herzlich Willkommen ' . $identity['username'] . '!';
}
?>
</div>
</div>
</div>
