<?php 
/**
 * ZF2 Buch Kapitel 13
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 13.11 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 13.11</h1>
<h3>Passwortdatei <code>digest.pw</code> für Digest HTTP Authentication</h3>
<pre>
luigi:Luigis Pizza-Service:6b150f7dc4cdc0fe1b16315482544685
francesca:Luigis Pizza-Service:d23e77cb95c9129102cd8452a9e10390
alessandro:Luigis Pizza-Service:b03fd2ec130d394f1af3960e3bb37017
valentina:Luigis Pizza-Service:8792865b2896655c5de293ef425a06c3
</pre>
</div>
</div>
