<?php 
/**
 * ZF2 Buch Kapitel 13
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Index view script
 * 
 * @package    Application
 */
?>
<h1>Listings - Kapitel 13</h1>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing1301">Listing 13.1</a></td>
<td>Einsatz von <code>Zend\Session\Container</code></td>
</tr>
<tr>
<td><a href="/listing/listing1302">Listing 13.2</a></td>
<td>SQL-Dump für Datenbanktabelle <code>sessions</code> für SQLite3</td>
</tr>
<tr>
<td><a href="/listing/listing1303">Listing 13.3</a></td>
<td>Session <code>SaveHandler</code> für <code>DbTableGateway</code> ändern</td>
</tr>
<tr>
<td><a href="/listing/listing1304">Listing 13.4</a></td>
<td>ACL mit <code>Zend\Permissions\Acl</code> definieren</td>
</tr>
<tr>
<td><a href="/listing/listing1305">Listing 13.5</a></td>
<td><code>Zend\Permissions\Acl</code> abfragen</td>
</tr>
<tr>
<td><a href="/listing/listing1306">Listing 13.6</a></td>
<td>ACL mit <code>Zend\Cache</code> speichern</td>
</tr>
<tr>
<td><a href="/listing/listing1307">Listing 13.7</a></td>
<td><code>Zend\Permissions\Rbac</code> mit vier Rollen definieren</td>
</tr>
<tr>
<td><a href="/listing/listing1308">Listing 13.8</a></td>
<td><code>Zend\Permissions\Rbac</code> abfragen</td>
</tr>
<tr>
<td><a href="/listing/listing1309">Listing 13.9</a></td>
<td>Passwortdatei <code>basic.pw</code> für Basic HTTP Authentication</td>
</tr>
<tr>
<td><a href="/listing/listing1310">Listing 13.10</a></td>
<td>Basic HTTP Authentication mit <code>Http</code> Adapter</td>
</tr>
<tr>
<td><a href="/listing/listing1311">Listing 13.11</a></td>
<td>Passwortdatei <code>digest.pw</code> für Digest HTTP Authentication</td>
</tr>
<tr>
<td><a href="/listing/listing1312">Listing 13.12</a></td>
<td>Digest HTTP Authentication mit <code>Http</code> Adapter</td>
</tr>
<tr>
<td><a href="/listing/listing1313">Listing 13.13</a></td>
<td>SQL-Dump für Datenbanktabelle <code>users</code> für SQLite3</td>
</tr>
<tr>
<td><a href="/listing/listing1314">Listing 13.14</a></td>
<td>Authentifizierung mit <code>DbTable</code> Adapter</td>
</tr>
<tr>
<td><a href="/listing/listing1315">Listing 13.15</a></td>
<td>Formulare zum Anmelden und Abmelden mit <code>Zend\Authentication</code></td>
</tr>
<tr>
<td><a href="/listing/listing1316">Listing 13.16</a></td>
<td><code>AuthenticationService</code> mit <code>DbTable</code> einsetzen</td>
</tr>
</tbody>
</table>
